spring.application.name=backend
#spring.datasource.url=jdbc:postgresql://localhost:5432/nightlife_explorer_db
#spring.datasource.username=tuo_username
#spring.datasource.password=tuo_password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/nightlife_explorer
spring.datasource.username=postgres
spring.datasource.password=123

# Configurazione JWT 44 CARATTERI
spring.jwt.secret=${JWT_SECRET}
#jwt.secret=G7dLkPzS3LmHqT9UwXyIbV28nHjPeR5ZGTRU77891Yht

# Durata del token in millisecondi 1 h
jwt.expiration=3600000

# Porta dell'applicazione
server.port=8080

# Configurazione Swagger (Springdoc)
#springdoc.api-docs.path=/api-docs
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html